#!/bin/sh

# $FreeBSD: head/audio/liquidsoap/files/liquidsoap.in 302141 2012-08-05 23:19:36Z dougb $
#
# PROVIDE: airtime_playout
# REQUIRE: NETWORKING airtime_liquidsoap
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable airtime_playout:
#
# airtime_playout_enable="YES"
#

. /etc/rc.subr

name=airtime_playout
rcvar=airtime_playout_enable

command=/usr/local/lib/airtime/pypo/bin/airtime-playout

load_rc_config $name

LANG=en_GB.UTF-8
export LANG
LC_ALL=en_GB.UTF-8
export LC_ALL

: ${airtime_playout_enable:="NO"}
: ${airtime_playout_pidfile:="/var/run/airtime-playout.pid"}
: ${airtime_playout_user:="root"}
: ${airtime_playout_group:="root"}

#required_files="${airtime_playout_config}"
#command_args="-q -d ${playout_config}"


start_cmd=airtime_playout_start
stop_cmd=airtime_playout_stop

airtime_playout_start () {
        if ! checkyesno airtime_playout_enable ; then
           return 0
        fi
        echo "Starting $command"

        daemon -p $airtime_playout_pidfile  $command
}

airtime_playout_stop () {
        # Send TERM after 5 seconds, wait at most 30 seconds.
        if [ -f $airtime_playout_pidfile ]
        then
        	kill -TERM `cat $airtime_playout_pidfile`
        	rm -f $airtime_playout_pidfile
	fi

}

run_rc_command "$1"
