#!/bin/sh

# $FreeBSD: head/audio/liquidsoap/files/liquidsoap.in 302141 2012-08-05 23:19:36Z dougb $
#
# PROVIDE: airtime_playout
# REQUIRE: NETWORKING airtime_liquidsoap
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable airtime_playout:
#
# airtime_playout_enable="YES"
#

. /etc/rc.subr

name=airtime_playout
rcvar=airtime_playout_enable

command=/usr/local/lib/airtime/pypo/bin/airtime-playout

load_rc_config $name

: ${airtime_playout_enable:="NO"}
: ${airtime_playout_pidfile:="/var/run/airtime-playout.pid"}
: ${airtime_playout_user:="root"}
: ${airtime_playout_group:="root"}

#required_files="${airtime_playout_config}"
#command_args="-q -d ${playout_config}"

run_rc_command "$1"
