#!/bin/sh

# $FreeBSD: head/audio/liquidsoap/files/liquidsoap.in 302141 2012-08-05 23:19:36Z dougb $
#
# PROVIDE: airtime-liquidsoap
# REQUIRE: NETWORKING icecast2 shoutcast
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable liquidsoap:
#
# liquidsoap_enable="YES"
#

. /etc/rc.subr

name=airtime_liquidsoap
rcvar=airtime_liquidsoap_enable

command=/usr/local/lib/airtime/pypo/bin/airtime-liquidsoap

load_rc_config $name

LANG=en_GB.UTF-8
export LANG
LC_ALL=en_GB.UTF-8
export LC_ALL

: ${airtime_liquidsoap_enable:="NO"}
: ${airtime_liquidsoap_pidfile:="/var/run/airtime-liquidsoap.pid"}
: ${airtime-liquidsoap_config:="/usr/local/lib/airtime/pypo/bin/liquidsoap_scripts/ls_script.liq"}
: ${airtime_liquidsoap_user:="pypo"}
: ${airtime_liquidsoap_group:="pypo"}

required_files="${airtime_liquidsoap_config}"
#command_args="-q -d ${liquidsoap_config}"

run_rc_command "$1"
