#!/usr/bin/env bash

virtualenv_bin="/usr/local/lib/airtime/airtime_virtualenv/bin/"
. ${virtualenv_bin}activate

invokePwd=$PWD

airtime_import_path="/usr/local/lib/airtime/utils/airtime-import/"
airtime_import_script="airtime-import.py"

api_client_path="/usr/local/lib/airtime/"
cd ${airtime_import_path}

exec 2>&1

export PYTHONPATH=${api_client_path}

# Note the -u when calling python! we need it to get unbuffered binary stdout and stderr
exec python -u ${airtime_import_path}${airtime_import_script} --dir "$invokePwd" "$@"

# EOF
