#!/bin/sh

# PROVIDE: airtime_media_monitor

. /etc/rc.subr

name=airtime_media_monitor
rcvar=airtime_media_monitor_enable

command=/usr/local/lib/airtime/media-monitor/airtime-media-monitor
pidfile=/var/run/airtime_media_monitor.pid

start_cmd=airtime_media_monitor_start
stop_cmd=airtime_media_monitor_stop

airtime_media_monitor_start () {
        if ! checkyesno airtime_media_monitor_enable ; then
           return 0
        fi
        echo "Starting $command"

        daemon -p $pidfile  $command
}

airtime_media_monitor_stop () {
        # Send TERM after 5 seconds, wait at most 30 seconds.
        kill -TERM `cat $pidfile`
        rm -f $PIDFILE
}

load_rc_config ${name}
run_rc_command "$1"
