#!/bin/bash
#-------------------------------------------------------------------------------
#  This script for a correct system environment for Airtime.
#
# Absolute path to this script
SCRIPT=`realpath $0`
# Absolute directory this script is in
SCRIPTPATH=`dirname $SCRIPT`

invokePwd=$PWD
cd $SCRIPTPATH

php -q airtime-check-system.php "$@" || exit 1
